export const menuData = {
  categories: [
    {
      id: 'sandwiches',
      name: 'Sandwiches',
      description: 'Layered favorites with rich cheese and savory fillings.',
      items: [
        {
          id: 1,
          category: 'Sandwiches',
          name: 'Tandoori Chicken and Cheese melt Sandwich',
          description: 'Tandoori chicken with melted cheese on grilled bread.',
          price: 900,
          bestseller: false,
          spicy: true,
          vegetarian: false,
          available: true,
        },
        {
          id: 2,
          category: 'Sandwiches',
          name: 'Grilled Vegetable and Cheese Sandwich',
          description: 'Grilled vegetables layered with melted cheese and herbs.',
          price: 700,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 3,
          category: 'Sandwiches',
          name: 'Grilled Chicken Beacon and Cheese Sandwich',
          description: 'Grilled chicken with smoky bacon and melted cheese.',
          price: 800,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 4,
          category: 'Sandwiches',
          name: 'Brown Deker With Cheese & Tomato Sandwich',
          description: 'Toasted brown bread with cheese, tomato and herbs.',
          price: 800,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 5,
          category: 'Sandwiches',
          name: 'Grilled Tuna Salad with Cheese Melt Sandwich',
          description: 'Grilled tuna salad finished with melty cheese.',
          price: 800,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 6,
          category: 'Sandwiches',
          name: 'Egg & Cheese Grilled Sandwich',
          description: 'Egg and cheese grilled to golden perfection.',
          price: 800,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 7,
          category: 'Sandwiches',
          name: 'Grilled Chicken Salad with cheese Sandwich',
          description: 'Grilled chicken salad with melted cheese in a toasted sandwich.',
          price: 800,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 8,
          category: 'Sandwiches',
          name: 'Club Sandwich stacked with layers of flavor',
          description: 'A stacked club sandwich with chicken, bacon, egg and cheese.',
          price: 1200,
          bestseller: true,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 9,
          category: 'Sandwiches',
          name: 'Devilled Chicken Sausage and Cheese Melt',
          description: 'Spiced chicken sausage melted with cheese for a bold sandwich.',
          price: 900,
          bestseller: false,
          spicy: true,
          vegetarian: false,
          available: true,
        },
      ],
    },
    {
      id: 'burgers',
      name: 'Burger',
      description: 'Premium burgers with cheesy, indulgent toppings.',
      items: [
        {
          id: 10,
          category: 'Burger',
          name: 'Mexican Chicken & Cheese Burger',
          description: 'A spicy chicken burger with melted cheese and Mexican flavor.',
          price: 1200,
          bestseller: false,
          spicy: true,
          vegetarian: false,
          available: true,
        },
        {
          id: 11,
          category: 'Burger',
          name: 'Chicken Blockbuster',
          description: 'Loaded chicken burger with bold toppings and rich cheese.',
          price: 1300,
          bestseller: true,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 12,
          category: 'Burger',
          name: 'Fried Fish Fillet With Cheese',
          description: 'Crispy fish fillet topped with melting cheese.',
          price: 1300,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 13,
          category: 'Burger',
          name: 'Golden Batter Fried Prawns & Cheese Burger',
          description: 'Crunchy prawns with melted cheese on a premium burger.',
          price: 1300,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
      ],
    },
    {
      id: 'submarine',
      name: 'Submarine',
      description: 'Submarine rolls filled with savory cheese and protein.',
      items: [
        {
          id: 14,
          category: 'Submarine',
          name: 'Mexican Chicken & Cheese Submarine',
          description: 'Spicy chicken and melted cheese in a submarine roll.',
          price: 1400,
          bestseller: false,
          spicy: true,
          vegetarian: false,
          available: true,
        },
        {
          id: 15,
          category: 'Submarine',
          name: 'Mongolina Chicken & Cheese Submarine',
          description: 'Savory Mongolian-style chicken with cheese and fresh fillings.',
          price: 1400,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 16,
          category: 'Submarine',
          name: 'Devillled Chicken & Cheese Submarine',
          description: 'Devilled chicken with melted cheese in a hearty submarine.',
          price: 1300,
          bestseller: false,
          spicy: true,
          vegetarian: false,
          available: true,
        },
        {
          id: 17,
          category: 'Submarine',
          name: 'Hot Butter Prawns & Cheese Submarine',
          description: 'Butter-poached prawns with cheese in a warm roll.',
          price: 1450,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 18,
          category: 'Submarine',
          name: 'Jumbo Hotdog With Cheese Submarine',
          description: 'Jumbo hotdog topped with melted cheese and premium sauce.',
          price: 1300,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
      ],
    },
    {
      id: 'wraps',
      name: 'Wraps',
      description: 'Soft wraps loaded with cheese and flavorful fillings.',
      items: [
        {
          id: 19,
          category: 'Wraps',
          name: 'Mexican Chicken & Cheese Wraps',
          description: 'Spicy chicken wrapped with melted cheese and fresh greens.',
          price: 1200,
          bestseller: false,
          spicy: true,
          vegetarian: false,
          available: true,
        },
        {
          id: 20,
          category: 'Wraps',
          name: 'Mongolian Chicken & Mozzarella Wraps',
          description: 'Mongolian-style chicken with mozzarella in a warm wrap.',
          price: 1200,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 21,
          category: 'Wraps',
          name: 'BBQ Prawns Wrap',
          description: 'Smoky BBQ prawns wrapped with melted cheese.',
          price: 1300,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 22,
          category: 'Wraps',
          name: 'Hot Batteree Cuttlefish  Wrap',
          description: 'Crispy battered cuttlefish and cheese wrapped warm.',
          price: 1000,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
      ],
    },
    {
      id: 'croissants',
      name: 'Croissants',
      description: 'Buttery croissants filled with cheese and savory proteins.',
      items: [
        {
          id: 23,
          category: 'Croissants',
          name: 'Egg & Mayo With Cheese Croissants',
          description: 'Egg mayo and cheese tucked in a flaky croissant.',
          price: 600,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 24,
          category: 'Croissants',
          name: 'Tandoori Chicken & Cheese Croissants',
          description: 'Spiced chicken and cheese folded into a golden croissant.',
          price: 700,
          bestseller: false,
          spicy: true,
          vegetarian: false,
          available: true,
        },
        {
          id: 25,
          category: 'Croissants',
          name: 'Chicken Bacon & Cheese Croissants',
          description: 'Chicken, bacon and cheese in a warm, flaky croissant.',
          price: 650,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 26,
          category: 'Croissants',
          name: 'Tuna Salad & Cheese Croissants',
          description: 'Tuna salad and cheese wrapped in buttery pastry.',
          price: 700,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 27,
          category: 'Croissants',
          name: 'Chicken Salad & Cheese Croissants',
          description: 'Chicken salad and melted cheese in a delicate croissant.',
          price: 900,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
      ],
    },
    {
      id: 'waffles',
      name: 'Waffles',
      description: 'Sweet and savory waffles finished with premium toppings.',
      items: [
        {
          id: 28,
          category: 'Waffles',
          name: 'Chicken Bacon & Cheese Waffle',
          description: 'Savory waffle topped with chicken, bacon and cheese.',
          price: 800,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 29,
          category: 'Waffles',
          name: 'Smoked Chicken & Cheese Waffle',
          description: 'Smoked chicken and cheese served on a golden waffle.',
          price: 900,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 30,
          category: 'Waffles',
          name: 'Egg & Cheese Waffle',
          description: 'Egg and cheese over a warm waffle for a rich breakfast bite.',
          price: 700,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 31,
          category: 'Waffles',
          name: 'Tandoori Chicken Waffle',
          description: 'Spiced chicken and melted cheese atop a crispy waffle.',
          price: 800,
          bestseller: false,
          spicy: true,
          vegetarian: false,
          available: true,
        },
        {
          id: 32,
          category: 'Waffles',
          name: 'Banana Waffle',
          description: 'Banana slices and sweet topping on a warm waffle.',
          price: 600,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 33,
          category: 'Waffles',
          name: 'Strawberry & Whipped Cream',
          description: 'Fresh strawberries and whipped cream on a waffle.',
          price: 700,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 34,
          category: 'Waffles',
          name: 'Fruity Waffle',
          description: 'A vibrant waffle topped with fresh fruit.',
          price: 900,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 35,
          category: 'Waffles',
          name: 'Waffle Surprise',
          description: 'A signature waffle with special toppings and flair.',
          price: 700,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 36,
          category: 'Waffles',
          name: 'Waffle with any topping (Chocolate/ Strawberry/ Blueberry)',
          description: 'Choose chocolate, strawberry or blueberry topping for your waffle.',
          price: 600,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
      ],
    },
    {
      id: 'drinks',
      name: 'Milkshake / Fresh Juice / Mojito',
      description: 'Chilled shakes, fresh juices and mojitos to refresh every order.',
      items: [
        {
          id: 37,
          category: 'Drinks',
          name: 'Vanilla milkshake',
          description: 'Classic creamy vanilla milkshake.',
          price: 800,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 38,
          category: 'Drinks',
          name: 'Chocolate Milkshake',
          description: 'Rich chocolate milkshake with smooth texture.',
          price: 800,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 39,
          category: 'Drinks',
          name: 'Strawberry Milkshake',
          description: 'Fresh strawberry milkshake with sweet cream.',
          price: 800,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 40,
          category: 'Drinks',
          name: 'Cookie Cream Milkshake',
          description: 'Creamy cookie shake with crunchy bits.',
          price: 900,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 41,
          category: 'Drinks',
          name: 'Choco Chip Milkshake',
          description: 'Chocolate chip shake with rich cream.',
          price: 900,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 42,
          category: 'Drinks',
          name: 'Rocky Road Milkshake ( Nuts & Marshmellows)',
          description: 'Indulgent rocky road shake with nuts and marshmallows.',
          price: 900,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 43,
          category: 'Drinks',
          name: 'Avacado',
          description: 'Creamy avocado juice for a refreshing treat.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 44,
          category: 'Drinks',
          name: 'Papaya',
          description: 'Sweet papaya juice served cold.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 45,
          category: 'Drinks',
          name: 'Orange',
          description: 'Fresh orange juice pressed to order.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 46,
          category: 'Drinks',
          name: 'Passion',
          description: 'Passion fruit juice with bright tropical notes.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 47,
          category: 'Drinks',
          name: 'Watermelon',
          description: 'Watermelon juice chilled for a refreshing finish.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 48,
          category: 'Drinks',
          name: 'Lime',
          description: 'Zesty lime juice with a crisp finish.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 49,
          category: 'Drinks',
          name: 'Lemon & Mint mojito',
          description: 'Refreshing lemon and mint mojito.',
          price: 600,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 50,
          category: 'Drinks',
          name: 'Strawberry Mojito',
          description: 'Sweet strawberry mojito with fresh mint.',
          price: 600,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 51,
          category: 'Drinks',
          name: 'Passion mojito',
          description: 'Tropical passion fruit mojito.',
          price: 600,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 52,
          category: 'Drinks',
          name: 'Caramel mojito',
          description: 'Sweet caramel mojito with mint.',
          price: 600,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 53,
          category: 'Drinks',
          name: 'Kivi mojito',
          description: 'Kiwi mojito with fresh mint and bright flavor.',
          price: 600,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 54,
          category: 'Drinks',
          name: 'Blue curacao Mojito',
          description: 'Blue curaçao mojito with vibrant tropical notes.',
          price: 800,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 55,
          category: 'Drinks',
          name: 'Lime & Mint Iced tea',
          description: 'Zesty lime iced tea with crisp mint.',
          price: 500,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 56,
          category: 'Drinks',
          name: 'Peach Tea Iced tea',
          description: 'Sweet peach iced tea brewed and chilled.',
          price: 600,
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
      ],
    },
    {
      id: 'special-dishes',
      name: 'Special Dishes',
      description: 'Shareable and indulgent dishes designed for a premium experience.',
      items: [
        {
          id: 57,
          category: 'Special Dishes',
          name: 'Fish & Chips',
          description: 'Classic fish and chips with crispy batter.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 58,
          category: 'Special Dishes',
          name: 'Chicken & Chips',
          description: 'Tender chicken served with seasoned chips.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 59,
          category: 'Special Dishes',
          name: 'Hot Honey Crispy Chicken Wings (6pcs)',
          description: 'Six crispy wings glazed in hot honey.',
          price: 'Ask',
          bestseller: false,
          spicy: true,
          vegetarian: false,
          available: true,
        },
        {
          id: 60,
          category: 'Special Dishes',
          name: 'Chicken Nuggets',
          description: 'Golden chicken nuggets served hot.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
      ],
    },
    {
      id: 'breakfast',
      name: 'Breakfast',
      description: 'Breakfast classics with hearty and comforting flavor.',
      items: [
        {
          id: 61,
          category: 'Breakfast',
          name: 'Milk Rice With Lunu Miris',
          description: 'Creamy milk rice served with spicy lunu miris.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 62,
          category: 'Breakfast',
          name: 'Kadala With Egg & Cheese',
          description: 'Spiced chickpeas with egg and melted cheese.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 63,
          category: 'Breakfast',
          name: 'Hot Cake With Chocolate Sauce',
          description: 'Warm pancakes topped with chocolate sauce.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 64,
          category: 'Breakfast',
          name: 'English Breafast',
          description: 'Full English breakfast with savory sides.',
          price: 1600,
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
      ],
    },
    {
      id: 'a-la-carte',
      name: 'A la Carte menu',
      description: 'Individual dishes for a tailored dining experience.',
      items: [
        {
          id: 65,
          category: 'A la Carte menu',
          name: 'Loaded Fries',
          description: 'Fries loaded with cheese and savory toppings.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 66,
          category: 'A la Carte menu',
          name: 'Cream Of Vegetable Soup',
          description: 'Smooth and creamy vegetable soup.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 67,
          category: 'A la Carte menu',
          name: 'Egg Soup',
          description: 'Warm egg soup with savory notes.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 68,
          category: 'A la Carte menu',
          name: 'Cream Of Chicken Soup',
          description: 'Rich chicken soup with creamy broth.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 69,
          category: 'A la Carte menu',
          name: 'Seafood Soup',
          description: 'Savory soup with a seafood blend.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 70,
          category: 'A la Carte menu',
          name: 'Sweet Corn Soup',
          description: 'Sweet corn soup with gentle spice.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 71,
          category: 'A la Carte menu',
          name: 'Chicken Lasagna',
          description: 'Layered chicken lasagna with cheese sauce.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 72,
          category: 'A la Carte menu',
          name: 'Chicken Kottu',
          description: 'Stir-fried kottu with chicken and spices.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 73,
          category: 'A la Carte menu',
          name: 'Roast Chicken Kottu',
          description: 'Roast chicken kottu with savory seasoning.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 74,
          category: 'A la Carte menu',
          name: 'Cheese & Chicken Kottu',
          description: 'Cheesy chicken kottu with rich flavor.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 75,
          category: 'A la Carte menu',
          name: 'Mongolian Chicken Kottu',
          description: 'Mongolian-style chicken kottu with bold sauce.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 76,
          category: 'A la Carte menu',
          name: 'Mongolian Seafood Kottu',
          description: 'Seafood kottu with Mongolian seasoning.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
        {
          id: 77,
          category: 'A la Carte menu',
          name: 'Vegetable Fried Rice',
          description: 'Savory fried rice with garden vegetables.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: true,
          available: true,
        },
        {
          id: 78,
          category: 'A la Carte menu',
          name: 'Egg Fried Rice',
          description: 'Classic egg fried rice with light seasoning.',
          price: 'Ask',
          bestseller: false,
          spicy: false,
          vegetarian: false,
          available: true,
        },
      ],
    },
  ],
};
